### ISSUE TITLE
Can't run project on local

### ISSUE THREAD

**Issue by tung-eh** [canhnd58/achromevement#16]
# Steps
I cloned project, then run `npm install`, it show the error:
```
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0npm/_locks/staging-8cea6c9c6a446933.lock for /Users/devops/Learnspace/achromevement/node_modules/.staging
error: pathspec '4.0' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
I tried to ignore this error and went to the next steps, I continued to got error when run `gulp build`:
```
[08:39:16] Requiring external module @babel/register
[08:39:16] Local gulp not found in ~/Learnspace/achromevement
[08:39:16] Try running: npm install gulp
```
Seems like the first error come when npm installing @babel/register, and `gulp` can't run because this module is missing
# Environment
- Node `8.11.2`
- npm `6.4.1`

**Comment by canhnd58** [comment]
Gulp v4 has been updated. Change package.json dependency from

    "gulp": "github:gulpjs/gulp#4.0"

to

    "gulp": "^4.0.0",
